copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\MyCode\GPIO_OutputInput\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\ADC_ContinuousScanMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\ADC_PwmTrigger\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\ADC_ResultMonitor\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\ADC_SingleCycleScanMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\ADC_SingleMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\BPWM_Capture\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\BPWM_DoubleBuffer\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\CAN_Set_MaskFilter\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\CAN_Test_MaskFilter\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\FMC_IAP\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\FMC_MultiBoot\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\FMC_RW\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\GPIO_EINTAndDebounce\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\GPIO_INT\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\GPIO_OutputInput\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\GPIO_PowerDown\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\I2C_EEPROM\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\I2C_GCMode_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\I2C_GCMode_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\I2C_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\I2C_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\I2C_Wakeup_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\I2C_Wakeup_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\PWM_Capture\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\PWM_DeadZone\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\PWM_DoubleBuffer\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\SPI_Loopback\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\SPI_MasterFifoMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\SPI_SlaveFifoMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\SYS_PLLClockOutput\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\TIMER_Capture\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\TIMER_Counter\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\TIMER_PeriodicINT\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\TIMER_PowerDown\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\UART_Autoflow_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\UART_Autoflow_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\UART_IrDA_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\UART_IrDA_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\UART_LIN\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\UART_RS485_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\UART_RS485_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\UART_TxRx_Function\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\WDT_PowerDown\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\WDT_TimeoutINT\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\WDT_TimeoutReset\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\RegBased\WWDT_CompareINT\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\Semihost\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\ADC_ContinuousScanMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\ADC_PwmTrigger\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\ADC_ResultMonitor\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\ADC_SingleCycleScanMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\ADC_SingleMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\BPWM_Capture\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\BPWM_DoubleBuffer\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\CAN_BasicMode_Receive\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\CAN_BasicMode_Transmit\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\CAN_NormalMode_Receive\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\CAN_NormalMode_Transmit\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\CAN_Wakeup\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\FMC_IAP\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\FMC_RW\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\GPIO_EINTAndDebounce\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\GPIO_INT\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\GPIO_OutputInput\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\GPIO_PowerDown\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\I2C_EEPROM\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\I2C_GCMode_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\I2C_GCMode_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\I2C_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\I2C_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\I2C_Wakeup_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\I2C_Wakeup_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\PWM_Capture\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\PWM_DeadZone\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\PWM_DoubleBuffer\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\SPI_Loopback\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\SPI_MasterFifoMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\SPI_SlaveFifoMode\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\SYS_PLLClockOutput\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\TIMER_Capture\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\TIMER_Counter\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\TIMER_Delay\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\TIMER_PeriodicINT\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\TIMER_PowerDown\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\UART_Autoflow_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\UART_Autoflow_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\UART_IrDA_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\UART_IrDA_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\UART_LIN\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\UART_RS485_Master\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\UART_RS485_Slave\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\UART_TxRx_Function\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\WDT_PowerDown\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\WDT_TimeoutINT\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\WDT_TimeoutReset\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\StdDriver\WWDT_CompareINT\KEIL\Nu_Link_Driver.ini
copy /Y Nu_Link_Driver.ini D:\MCU\FA8258\BSP\SampleCode\Template\Keil\Nu_Link_Driver.ini
